import React from 'react';
import { Text, StyleSheet, View, Button, TouchableOpacity, Image, ScrollView } from 'react-native';

const Vishnu = () => {
  return (
  <ScrollView>
    <View>
    <Text style={styles.titleStyle}>
        Vishnu
    </Text>
    <Text style={styles.textStyle}>
    "In the beginning of creation, the great Vishnu, desirous of creating the whole world,
    became threefold; Creator, Preserver, Destroyer. In order to create this world, the 
    Supreme Spirit produced from the right side of his body himself as Brahmā; then, in 
    order to preserve the world, he produced from his left side Vishnu; and in order to 
    destroy the world, he produced from the middle of his body the eternal Siva. Vishnu, one yet threefold, creates, preserves,
    and destroys: therefore let the pious make no difference between the three." (Wilkins 51).
    </Text>
    <Text style={styles.textStyle}>
    Vishnu, in the Rig-Veda, is said "to have established the heavens and the earth; to contain all the world
    in his strides; to have, with Indra, made the atmosphere wide, stretched out the worlds, produced the
    Sun, the Dawn, and Fire; to have received the homage of Varuna; whilst his greatness is described as
    having no limit within the ken of present or future beings. The attributes ascribed to Vishnu in some of
    these passages are such that, if the latter stood alone in the Rig-Veda, they might lead us to suppose
    that he was regarded by the Vedic Rishis as the chief of all the gods. But Indra is associated with
    Vishnu even in some of those texts in which the latter is most highly magnified: nay, in one place, the
    power by which Vishnu takes his three strides is described as being derived from Indra; in another text,
    Vishnu is represented as celebrating Indra's praise; whilst in another verse, Vishnu is said to have been
    generated by Soma.
    </Text>
    <Text style={styles.textStyle}>
    Madhusudana, the destroyer of Madhu; and Kaitabhajit, the conqueror of Kaitabha. These were two
    demons who issued from Vishnu's ear as he lay asleep on the serpent Sesha at the end of a Kalpa, * and
    were about to destroy Brahmā, as he sat on the lotus which sprang from Vishnu's navel, when this deity
    slew them, and hence obtained these names.</Text>
    <Text style={styles.textStyle}>
    Vaikunthanāth, "The Lord of Paradise."
    </Text>
    <Text style={styles.textStyle}>
    Kesava, "He who has excellent hair."
    </Text>
    <Text style={styles.textStyle}>
    Madhava, "Made of honey; or a descendant of Madhu."
    </Text>
    <Text style={styles.textStyle}>
    Swayambhu, "The self-existent one."
    </Text>
    <Text style={styles.textStyle}>
    Pitamvara, "He who wears yellow garments."
    </Text>
    <Text style={styles.textStyle}>
    Janārddana, "He who causes the people to worship."
    </Text>
    <Text style={styles.textStyle}>
    Vishvamvara, "The protector of the world."
    </Text>
    <Text style={styles.textStyle}>
    Hari, "The saviour; " lit. he who takes possession of.
    </Text>
    <Text style={styles.textStyle}>
    Ananta, "The endless."
    </Text>
    <Text style={styles.textStyle}>
    Dāmodara, "Bound with a rope."
    </Text>
    <Text style={styles.textStyle}>
    Mukunda, "The deliverer."
    </Text>
    <Text style={styles.textStyle}>
    Purusha, "The man," or "The spirit."
    </Text>
    <Text style={styles.textStyle}>
    Purushottama, "The supreme man or spirit."
    </Text>
    <Text style={styles.textStyle}>
    Yajneswara, "The lord of sacrifice."
    </Text>
    <Image
        style={{width: 100, height: 100}}
        source={{uri:'https://imgur.com/YytbEQt'}}
    />
    </View>
  </ScrollView>
  );
};

const styles = StyleSheet.create({
  titleStyle: {
    fontSize: 80,
    textAlign: 'center',
    fontFamily: 'Georgia',
    color: 'blue',
  },
  textStyle:{
    margin: 10,
    fontFamily: 'Georgia',
    fontSize: 30,
  }
});

export default Vishnu;
